name: content_placeholder_example
description: Demonstrates how to use the Content Placeholder plugin.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  content_placeholder:
    path: ../

flutter:
  uses-material-design: true