name: content_placeholder
description: A fluter plugin to make nice animated shimmer content placeholders.
version: 0.1.0
homepage: https://github.com/ctrleffive/content-placeholder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0-nullsafety.0